"""
Reporting phase entry point.

Reads /rover/output/map.json, generates report.md (with mermaid diagrams,
cited evidence, and LLM-narrated crisis + recommendations), and runs a
citation-grounding audit before writing the file.

Section layout:
    1. Executive summary               deterministic
    2. Crisis narrative                LLM call 1, deterministic fallback
    3. Cascade path                    deterministic
    4. Timeline to colony-wide crisis  deterministic (chained_cascades)
    5. The two survivors               deterministic
    6. Six critical signals            deterministic, with verbatim citations
    7. Reconciliation summary          deterministic
    8. Recommendations                 LLM call 2, deterministic fallback
    9. Methodology appendix            deterministic

See design_log.md Sessions 8–9.
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
import sys
from datetime import datetime
from pathlib import Path

from map.models import (
    ChainedCascade,
    ColonyMap,
    CommEntry,
    DependencyEdge,
    EdgeState,
    HistoricalEdge,
    LLMDerivedSignal,
    LogEntry,
    MetadataSignal,
    MetadataSignalType,
    PodNode,
)
from .audit import _CITATION_RE, build_citation_index, summarise_audit
from .validation import audit_llm_signals as _audit_llm_signals
from .llm_api import (
    CRISIS_NARRATIVE_TOOL,
    LLMClient,
    RECOMMENDATIONS_TOOL,
    load_prompt,
)

DEFAULT_OUTPUT_DIR     = Path(os.environ.get("OUTPUT_DIR", "/rover/output"))
DEFAULT_LLM_API_KEY    = os.environ.get("LLM_API_KEY")
DEFAULT_DELIVERABLE_DIR = Path(os.environ.get("DELIVERABLE_DIR", "")) if os.environ.get("DELIVERABLE_DIR") else None

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-7s  %(message)s",
    datefmt="%H:%M:%S",
    stream=sys.stdout,
)
logger = logging.getLogger(__name__)


# ── Citation helpers ────────────────────────────────────────────────────────

def _ts(t: datetime) -> str:
    return t.strftime("%Y-%m-%dT%H:%M:%SZ")

def cite_log(entry: LogEntry) -> str:
    return f"[pod:logs:{entry.pod_id}:{_ts(entry.timestamp)}]"

def cite_comm(entry: CommEntry) -> str:
    return f"[pod:comms:{entry.pod_id}:{_ts(entry.timestamp)}]"

def cite_edge(edge: DependencyEdge) -> str:
    return f"[edge:{edge.source}->{edge.target}:{edge.resource}]"

def cite_meta(pod_id: str, field: str) -> str:
    return f"[pod:metadata:{pod_id}:{field}]"

def cite_directive(did: str) -> str:
    return f"[directive:{did}]"

def pod_name(cm: ColonyMap, pid: str) -> str:
    pod = cm.pods.get(pid)
    return pod.display_name if pod else pid


# ── Citation sanitization (guards against LLM-hallucinated IDs) ─────────────

def _citation_valid(body: str, index: dict) -> bool:
    if body.startswith("pod:logs:"):
        return body[len("pod:logs:"):] in index["logs"]
    elif body.startswith("pod:comms:"):
        return body[len("pod:comms:"):] in index["comms"]
    elif body.startswith("pod:metadata:"):
        return body[len("pod:metadata:"):] in index["metadata"]
    elif body.startswith("edge:"):
        return body[len("edge:"):] in index["edges"]
    elif body.startswith("directive:"):
        return body[len("directive:"):] in index["directive"]
    return False


def _sanitize_text(text: str, index: dict) -> str:
    """Strip citations that don't resolve in the index from inline text."""
    return _CITATION_RE.sub(
        lambda m: m.group(0) if _citation_valid(m.group(1), index) else "",
        text,
    )


def _sanitize_evidence(ev: list[str], index: dict) -> list[str]:
    """Keep only evidence strings that contain at least one valid citation."""
    out = []
    for item in ev:
        m = _CITATION_RE.search(item)
        if m is None or _citation_valid(m.group(1), index):
            out.append(item)
    return out


# ── Section 1: Executive summary ────────────────────────────────────────────

def build_executive_summary(cm: ColonyMap) -> str:
    metrics = cm.metrics
    risk_top = sorted(
        metrics.risk_scores.values(), key=lambda r: r.overall_risk, reverse=True,
    )[:3]
    aquifer_chain = next(
        (c for c in metrics.chained_cascades if c.primary_trigger == "aquifer"), None,
    )

    lines: list[str] = []
    lines.append("# Selene Colony Infrastructure Assessment")
    lines.append("")
    lines.append(f"*Generated by autonomous mapping agent on {cm.crawled_at.strftime('%Y-%m-%d')}*")
    lines.append("")
    lines.append("## Executive Summary")
    lines.append("")

    n_pods = cm.pod_count()
    n_edges = len(cm.edges)
    n_unrec = cm.unreconciled_edge_count()
    n_dissolved = len(metrics.historical_edges)

    cw = aquifer_chain.time_to_colony_wide_hours if aquifer_chain else None
    lc = aquifer_chain.time_to_life_critical_hours if aquifer_chain else None
    surv_ids = [s.pod_id for s in (aquifer_chain.survivors if aquifer_chain else [])]
    surv = ", ".join(pod_name(cm, p) for p in surv_ids) if surv_ids else "none"

    lines.append(
        f"The Selene colony's {n_pods} habitat pods are wired into a single "
        f"load-bearing dependency: **Aquifer Module**. Through "
        f"{n_dissolved} consolidation events documented in the operational "
        f"logs, every redundancy that would catch an Aquifer failure has been "
        f"stripped from the graph."
    )
    lines.append("")

    if lc is not None and cw is not None:
        lines.append(
            f"A loss of Aquifer reaches **life-critical impact at T+{lc:.0f}h** "
            f"(Zephyr atmospheric processing) and **colony-wide impact at "
            f"T+{cw:.0f}h** (Medica triple-supply failure). Only **{surv}** "
            f"survive, by virtue of independent power and water systems "
            f"rather than colony-level redundancy."
        )
    else:
        lines.append(
            f"A loss of Aquifer triggers a colony-wide cascade. Only **{surv}** "
            f"survive."
        )
    lines.append("")

    lines.append(f"The dependency graph contains {n_edges} edges, of which "
                 f"**{n_unrec} are unreconciled** — declared by only one of the "
                 f"two pods involved. These mismatches are the most analytically "
                 f"interesting findings in the assessment.")
    lines.append("")

    lines.append("### Top 3 Pods by Composite Risk")
    lines.append("")
    lines.append("| Pod | Overall Risk | Blast Radius | Corroborated SPOF Signals |")
    lines.append("|---|---:|---:|---:|")
    for rs in risk_top:
        lines.append(
            f"| {pod_name(cm, rs.pod_id)} "
            f"| {rs.overall_risk:.3f} "
            f"| {rs.blast_radius_score:.0%} "
            f"| {rs.spof_corroboration_count}/4 |"
        )
    lines.append("")
    return "\n".join(lines)


# ── Section 2: Crisis narrative (LLM with deterministic fallback) ───────────

def _llm_context_blocks(cm: ColonyMap) -> dict[str, str]:
    """Compact JSON context for LLM prompts."""
    aquifer = next(
        (c for c in cm.metrics.chained_cascades if c.primary_trigger == "aquifer"), None,
    )
    cascade_data = json.dumps(aquifer.model_dump(mode="json"), indent=2) if aquifer else "{}"
    historical = sorted(
        cm.metrics.historical_edges, key=lambda h: h.dissolved_at,
    )
    historical_data = json.dumps(
        [
            {
                "dissolved_at":   _ts(h.dissolved_at),
                "source":         h.source,
                "target":         h.target,
                "resource":       h.resource,
                "still_declared": h.still_declared,
                "log_pod":        h.log_pod,
                "evidence_text":  h.evidence_text,
            }
            for h in historical
        ],
        indent=2,
    )
    metadata_data = json.dumps(
        [
            {
                "pod_id":      s.pod_id,
                "field":       s.field,
                "value":       s.value,
                "signal_type": s.signal_type.value,
                "description": s.description,
            }
            for s in cm.metrics.metadata_signals
            if s.signal_type in (
                MetadataSignalType.NO_BACKUP,
                MetadataSignalType.STALE_REFERENCE,
            )
        ],
        indent=2,
    )
    llm_data = json.dumps(
        [
            {
                "source": s.source_pod,
                "target": s.target_pod,
                "type":   s.relationship_type.value,
                "conf":   s.confidence,
                "quote":  s.evidence_quote[:160],
            }
            for s in cm.metrics.llm_derived_signals[:12]
        ],
        indent=2,
    )

    # Build verified citation catalogs so the LLM can only use real IDs.
    index = build_citation_index(cm)
    edge_catalog = "\n".join(
        f"  [edge:{eid}]" for eid in sorted(index["edges"])
    )
    directive_catalog = "\n".join(
        f"  [directive:{d}]" for d in sorted(index["directive"])
    )
    comms_catalog = "\n".join(
        f"  [pod:comms:{c}]" for c in sorted(index["comms"])
    )
    log_catalog = "\n".join(
        f"  [pod:logs:{l}]" for l in sorted(index["logs"])
    )

    return {
        "cascade_data":      cascade_data,
        "historical_data":   historical_data,
        "metadata_data":     metadata_data,
        "llm_data":          llm_data,
        "edge_catalog":      edge_catalog,
        "directive_catalog": directive_catalog,
        "comms_catalog":     comms_catalog,
        "log_catalog":       log_catalog,
    }


async def build_crisis_section(cm: ColonyMap, llm: LLMClient) -> str:
    """LLM-narrated crisis paragraphs with deterministic fallback."""
    lines = ["## The Crisis: Aquifer as Transitive Single Point of Failure", ""]

    template = load_prompt("CRISIS_NARRATIVE")
    prompt = template.format(**_llm_context_blocks(cm))

    result = await llm.call_with_tool(CRISIS_NARRATIVE_TOOL, prompt, max_tokens=2000)
    if result and result.get("paragraphs"):
        index = build_citation_index(cm)
        if result.get("headline"):
            lines.append(f"**{_sanitize_text(result['headline'], index)}**")
            lines.append("")
        for para in result["paragraphs"]:
            lines.append(_sanitize_text(para, index))
            lines.append("")
        return "\n".join(lines)

    # Deterministic fallback — built directly from data
    return _crisis_fallback(cm, lines)


def _crisis_fallback(cm: ColonyMap, lines: list[str]) -> str:
    metrics = cm.metrics
    chronological = sorted(metrics.historical_edges, key=lambda h: h.dissolved_at)

    aquifer_no_backup = next(
        (s for s in metrics.metadata_signals
         if s.pod_id == "aquifer" and s.signal_type == MetadataSignalType.NO_BACKUP),
        None,
    )

    lines.append(
        f"**Aquifer Module is the colony's single point of failure for water, and the "
        f"failure mode is colony-wide.** The metadata field "
        f"`backup_systems=0` "
        + (cite_meta("aquifer", aquifer_no_backup.field) if aquifer_no_backup else "")
        + " confirms zero redundancy; "
        f"throughput is at "
        f"{cm.pods['aquifer'].info.metadata.get('throughput_l_day', 0)}/"
        f"{cm.pods['aquifer'].info.metadata.get('rated_capacity_l_day', 0)} "
        f"L/day "
        + cite_meta("aquifer", "throughput_l_day")
        + " — 93% utilization."
    )
    lines.append("")
    lines.append(
        "The single-source state was reached through a sequence of operational "
        "decisions, each individually rational:"
    )
    lines.append("")
    for h in chronological[:6]:
        date = _ts(h.dissolved_at)[:10]
        lines.append(
            f"- **{date}** — {h.source} → {h.target} [{h.resource}] dissolved. "
            f"[pod:logs:{h.log_pod}:{_ts(h.dissolved_at)}]"
            + (" — *formal dependency declaration is now stale*" if h.still_declared else "")
        )
    lines.append("")
    lines.append(
        f"The cumulative effect: {len(chronological)} formal "
        f"dependency dissolutions, {sum(1 for h in chronological if h.still_declared)} of "
        f"which left a stale formal declaration in the graph."
    )
    lines.append("")
    return "\n".join(lines)


# ── Section 3: Cascade path (deterministic) ─────────────────────────────────

def build_cascade_path(cm: ColonyMap) -> str:
    lines = ["## The Cascade Path", ""]
    aquifer_chain = next(
        (c for c in cm.metrics.chained_cascades if c.primary_trigger == "aquifer"), None,
    )
    if aquifer_chain is None:
        lines.append("*No chained cascade for Aquifer was computed.*")
        return "\n".join(lines)

    lines.append(
        "The following ordered cascade is computed deterministically from the "
        "operational dependency graph, the chained-cascade simulation in "
        "metrics.py, and the pessimistic chaining model (Decision 26)."
    )
    lines.append("")

    direct_water = [
        e for e in cm.edges
        if e.target == "aquifer"
        and e.state in (EdgeState.RECONCILED, EdgeState.DEP_ONLY)
    ]
    lines.append(
        f"**1. Aquifer fails (T+0).** {len(direct_water)} pods lose their water "
        f"resource immediately:"
    )
    for e in direct_water:
        lines.append(
            f"   - {pod_name(cm, e.source)} loses `{e.resource}` "
            f"({e.criticality.value}, {e.state.value}) {cite_edge(e)}"
        )
    lines.append("")

    helios_event = next(
        (e for e in aquifer_chain.events if e.pod_id == "helios"), None,
    )
    if helios_event and helios_event.cumulative_hours is not None:
        ev = helios_event.secondary_offset_evidence or helios_event.evidence_source
        lines.append(
            f"**2. Helios degrades (T+{helios_event.cumulative_hours:.0f}h).** "
            f"Inferred — there is no `battery_thermal_hours` field on Helios. "
            f"The estimate is grounded in `coolant_loop=aquifer-primary` "
            + cite_meta("helios", "coolant_loop")
            + f" plus the formal decommission of the Vault backup coolant loop "
              f"in 2094-02 "
            + cite_directive("2094-011")
            + f". Evidence string: `{ev}`. Pods that depend on Helios for "
              f"electrical_power lose their supply at this point."
        )
        lines.append("")

    timed_secondary = [
        e for e in aquifer_chain.events
        if e.cumulative_hours is not None and e.pod_id not in ("helios",)
    ]
    timed_secondary.sort(key=lambda e: e.cumulative_hours)
    n = 3
    for evt in timed_secondary:
        flags = []
        if evt.is_life_critical: flags.append("life-critical")
        if evt.is_compound:      flags.append("compound")
        flag_str = f" [{', '.join(flags)}]" if flags else ""
        lines.append(
            f"**{n}. {pod_name(cm, evt.pod_id)} fails (T+{evt.cumulative_hours:.0f}h).**{flag_str} "
            f"{evt.failure_mode}. "
            f"({evt.inference_confidence})"
        )
        lines.append("")
        n += 1

    untimed = [e for e in aquifer_chain.events if e.cumulative_hours is None]
    if untimed:
        lines.append(
            f"**{n}. Untimed downstream failures.** The following pods lose a "
            f"resource but the colony's metadata does not provide a survival "
            f"window for their lost resource. They fail somewhere in the "
            f"T+{aquifer_chain.time_to_life_critical_hours or 48:.0f}h–T+72h "
            f"window:"
        )
        for evt in untimed:
            lines.append(
                f"   - {pod_name(cm, evt.pod_id)}: {evt.failure_mode}"
            )
        lines.append("")

    return "\n".join(lines)


# ── Section 4: Timeline to colony-wide crisis ───────────────────────────────

def build_timeline(cm: ColonyMap) -> str:
    lines = ["## Timeline to Colony-Wide Crisis", ""]
    aquifer_chain = next(
        (c for c in cm.metrics.chained_cascades if c.primary_trigger == "aquifer"), None,
    )
    if aquifer_chain is None:
        lines.append("*No chained cascade available.*")
        return "\n".join(lines)

    helios_offset = aquifer_chain.inference_parameters.get(
        "helios_coolant_degradation_hours", 48.0,
    )
    lines.append(
        f"Inference parameter in use: "
        f"`helios_coolant_degradation_hours = {helios_offset:.0f}h` "
        f"(see Decision 25)."
    )
    lines.append("")

    direct_water_count = len([
        e for e in cm.edges
        if e.target == "aquifer"
        and e.state in (EdgeState.RECONCILED, EdgeState.DEP_ONLY)
    ])

    lines.append("| Time After Aquifer Failure | Event | Source |")
    lines.append("|---|---|---|")
    lines.append(f"| T+0   | Aquifer fails; direct water loss to {direct_water_count} pods "
                 f"| `cascade_simulations[aquifer].direct_dependents` |")
    lines.append(f"| T+{helios_offset:.0f}h | Helios power degradation begins "
                 f"| inferred (`helios_coolant_degradation_hours`) |")

    timed = sorted(
        [e for e in aquifer_chain.events if e.cumulative_hours is not None and e.pod_id != "helios"],
        key=lambda e: e.cumulative_hours,
    )
    for evt in timed:
        if evt.pod_id == "zephyr":
            note = "atmospheric processing fails (4h backup_power_hours)"
        elif evt.pod_id == "medica":
            note = "loses medical_oxygen (6h oxygen_reserve_hours)"
        else:
            note = evt.failure_mode
        lines.append(
            f"| T+{evt.cumulative_hours:.0f}h | {pod_name(cm, evt.pod_id)} — {note} "
            f"| `chained_cascades[aquifer]` ({evt.inference_confidence}) |"
        )

    if aquifer_chain.time_to_colony_wide_hours is not None:
        cw = aquifer_chain.time_to_colony_wide_hours
        lines.append(f"| T+72h | Colony-wide crisis. Only "
                     + ", ".join(pod_name(cm, s.pod_id) for s in aquifer_chain.survivors)
                     + f" operational (computed life-critical envelope: T+{cw:.0f}h) "
                     f"| narrative threshold |")
    lines.append("")
    return "\n".join(lines)


# ── Section 5: The two survivors ────────────────────────────────────────────

def build_survivors(cm: ColonyMap) -> str:
    lines = ["## The Two Survivors", ""]
    aquifer_chain = next(
        (c for c in cm.metrics.chained_cascades if c.primary_trigger == "aquifer"), None,
    )
    if aquifer_chain is None or not aquifer_chain.survivors:
        lines.append("*No survivor analysis available.*")
        return "\n".join(lines)

    for sv in aquifer_chain.survivors:
        lines.append(f"### {pod_name(cm, sv.pod_id)}")
        lines.append("")
        lines.append(f"**{sv.reason}**")
        lines.append("")
        for e in sv.evidence:
            if e.startswith("metadata:"):
                # Convert "metadata:field=value" → "[pod:metadata:pod:field] = value"
                rest = e[len("metadata:"):]
                if "=" in rest:
                    field, value = rest.split("=", 1)
                    lines.append(f"- {cite_meta(sv.pod_id, field)} = `{value}`")
                else:
                    lines.append(f"- {e}")
            else:
                lines.append(f"- {e}")
        lines.append("")

    return "\n".join(lines)


# ── Section 6: Six critical signals ─────────────────────────────────────────

def build_signals(cm: ColonyMap) -> str:
    lines = ["## Six Critical Signals", ""]
    lines.append("Each signal below is grounded in a specific evidence chain "
                 "from `map.json`. Citations are validated by `audit.py` "
                 "before publish.")
    lines.append("")

    # Signal 1: Prometheus stale dep
    prom_stale = next(
        (e for e in cm.edges if e.source == "prometheus" and e.target == "aquifer"), None,
    )
    prom_meta = next(
        (s for s in cm.metrics.metadata_signals
         if s.pod_id == "prometheus" and s.signal_type == MetadataSignalType.STALE_REFERENCE),
        None,
    )
    prom_hist = sorted(
        [h for h in cm.metrics.historical_edges
         if "prometheus" in (h.source, h.target) and h.resource == "water"],
        key=lambda h: h.dissolved_at,
    )

    lines.append("### Signal 1 — Prometheus has a stale water dependency on Aquifer")
    lines.append("")
    if prom_stale:
        lines.append(f"- Edge {cite_edge(prom_stale)} — state `{prom_stale.state.value}` "
                     f"(prometheus declares it; aquifer's `/supplies` does not list prometheus)")
    if prom_meta:
        lines.append(f"- Metadata {cite_meta('prometheus', prom_meta.field)} = "
                     f"`{prom_meta.value}` — flagged STALE_REFERENCE because the "
                     f"direct connection was sealed in 2093-10")
    for h in prom_hist[:2]:
        lines.append(f"- Log {cite_log(_synth_log(h))} — \"{h.evidence_text[:140]}…\"")
    lines.append("- **Implication:** Prometheus actually depends transitively on "
                 "Hydroponics for water, which itself depends on Aquifer + Zephyr — "
                 "the formal graph is incomplete.")
    lines.append("")

    # Signal 2: Vault decommissioned
    vault_meta = cm.pods["vault"].info.metadata if "vault" in cm.pods else {}
    vault_hist = sorted(
        [h for h in cm.metrics.historical_edges
         if "vault" in (h.source, h.target)],
        key=lambda h: h.dissolved_at,
    )
    lines.append("### Signal 2 — Vault's safety-net role has been decommissioned")
    lines.append("")
    if "decommissioned_reserves" in vault_meta:
        lines.append(f"- Metadata {cite_meta('vault', 'decommissioned_reserves')} = "
                     f"`{vault_meta['decommissioned_reserves']}`")
    for h in vault_hist[:3]:
        lines.append(f"- Log {cite_log(_synth_log(h))} (`{_ts(h.dissolved_at)[:10]}`) — "
                     f"\"{h.evidence_text[:140]}…\"")
    lines.append("- **Implication:** the safety net that would catch an Aquifer "
                 "failure no longer exists.")
    lines.append("")

    # Signal 3: Helios coolant criticality mislabeled
    helios_coolant = next(
        (e for e in cm.edges if e.source == "helios" and e.target == "aquifer"), None,
    )
    lines.append("### Signal 3 — Helios's Aquifer coolant dependency is mislabeled `medium`")
    lines.append("")
    if helios_coolant:
        lines.append(f"- Edge {cite_edge(helios_coolant)} — declared criticality "
                     f"`{helios_coolant.criticality.value}`")
    if "coolant_loop" in cm.pods.get("helios", PodNode(id="helios", hostname="", port=0)).info.metadata if cm.pods.get("helios") and cm.pods["helios"].info else False:
        lines.append(f"- Metadata {cite_meta('helios', 'coolant_loop')} = "
                     f"`{cm.pods['helios'].info.metadata['coolant_loop']}` — sole source")
    helios_dissolved = [h for h in cm.metrics.historical_edges
                        if h.source == "helios" and h.target == "vault"]
    for h in helios_dissolved[:1]:
        lines.append(f"- Log {cite_log(_synth_log(h))} — backup coolant from Vault "
                     f"formally decommissioned: \"{h.evidence_text[:120]}…\"")
    lines.append("- **Implication:** a `medium` dependency is operationally "
                 "mission-critical. Without coolant, the entire colony power "
                 "grid degrades within ~48h.")
    lines.append("")

    # Signal 4: Zephyr retired reclamation
    zephyr_meta = cm.pods["zephyr"].info.metadata if "zephyr" in cm.pods else {}
    zephyr_hist = [h for h in cm.metrics.historical_edges
                   if h.log_pod == "zephyr"]
    lines.append("### Signal 4 — Zephyr retired its internal humidity reclamation")
    lines.append("")
    if "humidity_reclaim_pct" in zephyr_meta:
        lines.append(f"- Metadata {cite_meta('zephyr', 'humidity_reclaim_pct')} = "
                     f"`{zephyr_meta['humidity_reclaim_pct']}`")
    if "backup_power_hours" in zephyr_meta:
        lines.append(f"- Metadata {cite_meta('zephyr', 'backup_power_hours')} = "
                     f"`{zephyr_meta['backup_power_hours']}` (4h)")
    for h in zephyr_hist[:1]:
        lines.append(f"- Log {cite_log(_synth_log(h))} (`{_ts(h.dissolved_at)[:10]}`) — "
                     f"\"{h.evidence_text[:140]}…\"")
    lines.append("- **Implication:** zero humidity buffer + 4h power backup = "
                 "Zephyr is the colony's life-support fastest-failure path.")
    lines.append("")

    # Signal 5: Aquifer near capacity
    aq_meta = cm.pods["aquifer"].info.metadata if "aquifer" in cm.pods else {}
    util = (
        aq_meta["throughput_l_day"] / aq_meta["rated_capacity_l_day"] * 100
        if "throughput_l_day" in aq_meta and "rated_capacity_l_day" in aq_meta
        else None
    )
    lines.append("### Signal 5 — Aquifer is operating near capacity with zero backup")
    lines.append("")
    if util is not None:
        lines.append(f"- {cite_meta('aquifer', 'throughput_l_day')} = "
                     f"`{aq_meta['throughput_l_day']}` L/day, "
                     f"{cite_meta('aquifer', 'rated_capacity_l_day')} = "
                     f"`{aq_meta['rated_capacity_l_day']}` L/day → **{util:.1f}% utilization**")
    if "backup_systems" in aq_meta:
        lines.append(f"- {cite_meta('aquifer', 'backup_systems')} = `{aq_meta['backup_systems']}` — "
                     f"no redundancy")
    lines.append("- **Implication:** Aquifer has no headroom for incident response "
                 "and no fallback if it fails.")
    lines.append("")

    # Signal 6: Reconciliation discrepancies
    n_dep_only = sum(1 for e in cm.edges if e.state == EdgeState.DEP_ONLY)
    n_supply_only = sum(1 for e in cm.edges if e.state == EdgeState.SUPPLY_ONLY)
    lines.append("### Signal 6 — The declared graph disagrees with itself")
    lines.append("")
    lines.append(f"- Total edges: {len(cm.edges)}")
    lines.append(f"- DEP_ONLY (source declares dep; target's `/supplies` omits source): "
                 f"**{n_dep_only}**")
    lines.append(f"- SUPPLY_ONLY (target declares supply; source's `/dependencies` "
                 f"omits target): **{n_supply_only}**")
    lines.append("- **Implication:** the declared dependency graph is incomplete. "
                 "Sixteen mismatches are documented in `phases/reconciliation_audit.txt`.")
    lines.append("")
    return "\n".join(lines)


def _synth_log(h: HistoricalEdge) -> LogEntry:
    """Synthesise a LogEntry shape for cite_log() — we have h.log_pod + h.dissolved_at."""
    return LogEntry(
        timestamp=h.dissolved_at,
        pod_id=h.log_pod,
        event="dissolution",
        detail=h.evidence_text,
    )


# ── Section 7: Reconciliation summary ───────────────────────────────────────

def build_reconciliation_summary(cm: ColonyMap) -> str:
    lines = ["## Reconciliation Audit Summary", ""]
    n_total = len(cm.edges)
    n_unrec = cm.unreconciled_edge_count()
    n_dep   = sum(1 for e in cm.edges if e.state == EdgeState.DEP_ONLY)
    n_sup   = sum(1 for e in cm.edges if e.state == EdgeState.SUPPLY_ONLY)

    lines.append(f"- Total edges: **{n_total}** "
                 f"(reconciled: {n_total - n_unrec}; unreconciled: {n_unrec})")
    lines.append(f"- DEP_ONLY: {n_dep}")
    lines.append(f"- SUPPLY_ONLY: {n_sup}")
    lines.append("")

    dep_only_edges = [e for e in cm.edges if e.state == EdgeState.DEP_ONLY]
    if dep_only_edges:
        lines.append("### Ghost dependencies (highest priority)")
        lines.append("")
        for e in dep_only_edges:
            lines.append(
                f"- {cite_edge(e)} `{e.criticality.value}` — "
                f"{pod_name(cm, e.source)} declares dep on "
                f"{pod_name(cm, e.target)} for `{e.resource}`; "
                f"{pod_name(cm, e.target)}'s `/supplies` omits the relationship."
            )
        lines.append("")

    lines.append("Full machine-readable reconciliation in "
                 "`phases/reconciliation_audit.txt`.")
    lines.append("")
    return "\n".join(lines)


# ── Section 8: Recommendations (LLM with deterministic fallback) ────────────

async def build_recommendations(cm: ColonyMap, llm: LLMClient) -> str:
    lines = ["## Recommendations", ""]
    template = load_prompt("RECOMMENDATIONS")
    prompt = template.format(**_llm_context_blocks(cm))

    result = await llm.call_with_tool(RECOMMENDATIONS_TOOL, prompt, max_tokens=4096)
    if result and result.get("actions"):
        index = build_citation_index(cm)
        lines.append("| # | Action | Priority | Effort |")
        lines.append("|---|---|---|---|")
        for i, a in enumerate(result["actions"], start=1):
            lines.append(
                f"| {i} | {a.get('title', '')} "
                f"| {a.get('priority', '?')} "
                f"| {a.get('effort', '?')} |"
            )
        lines.append("")
        for i, a in enumerate(result["actions"], start=1):
            lines.append(f"### {i}. {a.get('title', '')}")
            lines.append("")
            lines.append(_sanitize_text(a.get("rationale", ""), index))
            lines.append("")
            ev = _sanitize_evidence(a.get("evidence", []) or [], index)
            if ev:
                lines.append("**Evidence:**")
                for c in ev:
                    lines.append(f"- {c}")
                lines.append("")
        return "\n".join(lines)

    return _recommendations_fallback(cm, lines)


def _recommendations_fallback(cm: ColonyMap, lines: list[str]) -> str:
    """Deterministic recommendations derived from historical_edges + metadata."""
    lines.append("*LLM-generated recommendations unavailable; deterministic "
                 "recommendations follow.*")
    lines.append("")

    # 1. Restore Vault water reserve
    vault_water = next(
        (h for h in cm.metrics.historical_edges
         if h.target == "aquifer" and h.source == "vault"), None,
    )
    if vault_water:
        lines.append("### 1. Restore Vault water reserve (CRITICAL, large effort)")
        lines.append("")
        lines.append(
            f"The Vault water backup was decommissioned on "
            f"`{_ts(vault_water.dissolved_at)[:10]}` "
            f"{cite_log(_synth_log(vault_water))}. Aquifer is now "
            f"single-source with `backup_systems=0` "
            + cite_meta("aquifer", "backup_systems")
            + ". Restoring this reserve is the highest-impact remediation."
        )
        lines.append("")

    # 2. Restore Helios coolant backup
    helios_coolant_dis = next(
        (h for h in cm.metrics.historical_edges
         if h.source == "helios" and h.target == "vault"), None,
    )
    if helios_coolant_dis:
        lines.append("### 2. Restore secondary coolant loop for Helios (CRITICAL, medium effort)")
        lines.append("")
        lines.append(
            f"Helios's backup coolant from Vault was formally decommissioned "
            f"`{_ts(helios_coolant_dis.dissolved_at)[:10]}` "
            f"{cite_log(_synth_log(helios_coolant_dis))}. With "
            + cite_meta("helios", "coolant_loop")
            + " = `aquifer-primary` as the only source, an Aquifer outage "
              "drives the colony power grid offline within ~48h."
        )
        lines.append("")

    # 3. Update Prometheus metadata + formal dep
    lines.append("### 3. Reconcile Prometheus's stale water dependency (HIGH, small effort)")
    lines.append("")
    prom_meta = cm.pods.get("prometheus").info.metadata if cm.pods.get("prometheus") and cm.pods["prometheus"].info else {}
    if "water_source" in prom_meta:
        lines.append(
            f"{cite_meta('prometheus', 'water_source')} = `{prom_meta['water_source']}` "
            f"contradicts the actual operational state. The formal "
            f"`/dependencies` declaration "
            + cite_edge(next(e for e in cm.edges if e.source == 'prometheus' and e.target == 'aquifer'))
            + f" should be updated to reflect the rerouting through "
              f"Hydroponics (logged 2093-09-30)."
        )
        lines.append("")

    # 4. Reactivate Zephyr humidity reclamation
    zephyr_hist = next(
        (h for h in cm.metrics.historical_edges if h.log_pod == "zephyr"), None,
    )
    if zephyr_hist:
        lines.append("### 4. Reactivate Zephyr humidity reclamation loop (HIGH, large effort)")
        lines.append("")
        lines.append(
            f"Zephyr retired its internal reclamation on "
            f"`{_ts(zephyr_hist.dissolved_at)[:10]}` "
            f"{cite_log(_synth_log(zephyr_hist))}. With "
            + cite_meta("zephyr", "humidity_reclaim_pct")
            + " = 0 and "
            + cite_meta("zephyr", "backup_power_hours")
            + " = 4, Zephyr is the fastest-failure path on a power-or-water "
              "loss."
        )
        lines.append("")

    # 5. Re-classify Helios coolant criticality
    lines.append("### 5. Re-classify Helios coolant_water dep from `medium` → `critical` (MEDIUM, small effort)")
    lines.append("")
    helios_aq = next((e for e in cm.edges if e.source == "helios" and e.target == "aquifer"), None)
    if helios_aq:
        lines.append(
            f"{cite_edge(helios_aq)} is currently `{helios_aq.criticality.value}` "
            f"but cascade analysis shows it is mission-critical. Updating the "
            f"label aligns operational priorities with reality."
        )
        lines.append("")

    # 6. Aquifer headroom
    lines.append("### 6. Add Aquifer throughput headroom (HIGH, large effort)")
    lines.append("")
    aq_meta = cm.pods["aquifer"].info.metadata if "aquifer" in cm.pods else {}
    if "throughput_l_day" in aq_meta and "rated_capacity_l_day" in aq_meta:
        util = aq_meta["throughput_l_day"] / aq_meta["rated_capacity_l_day"] * 100
        lines.append(
            f"Current utilization: **{util:.1f}%** "
            + cite_meta("aquifer", "throughput_l_day")
            + " against "
            + cite_meta("aquifer", "rated_capacity_l_day")
            + ". Adding capacity ahead of Phase 3 expansion is necessary to "
              "maintain safety margin."
        )
        lines.append("")

    return "\n".join(lines)


# ── Mermaid diagrams ─────────────────────────────────────────────────────────

def build_mermaid_dependency_graph(cm: ColonyMap) -> str:
    """Operational dependency graph — RECONCILED + DEP_ONLY edges only.

    Color scheme:
        red   — primary SPOF (Aquifer)
        amber — high-criticality compound pods (Helios)
        green — survivors (Sentinel, Nexus)
        gray  — everyone else
    """
    lines: list[str] = []
    lines.append("```mermaid")
    lines.append("graph LR")
    lines.append("    classDef spof     fill:#ff6b6b,stroke:#c92a2a,color:white,font-weight:bold")
    lines.append("    classDef compound fill:#ffd43b,stroke:#fab005,color:#333")
    lines.append("    classDef survivor fill:#51cf66,stroke:#2f9e44,color:white")
    lines.append("    classDef pod      fill:#e9ecef,stroke:#868e96,color:#333")
    lines.append("    linkStyle default stroke:#868e96")
    lines.append("")

    # Node definitions (deduplicated, displayed name only)
    spofs    = {"aquifer"}
    compound = {"helios"}
    survivors = {"sentinel", "nexus"}
    for pid, pod in cm.pods.items():
        name = pod.display_name.replace(" ", "<br/>")
        node_id = pid.upper()
        lines.append(f"    {node_id}[\"{name}\"]")
    lines.append("")

    # Edges — operational only
    for e in cm.edges:
        if e.state == EdgeState.SUPPLY_ONLY:
            continue
        # Compact resource label for readability
        res = e.resource.replace("_", " ")
        if e.criticality.value in ("critical", "high"):
            line_style = "==>"  # bold for critical
        else:
            line_style = "-->"
        lines.append(f"    {e.source.upper()} {line_style}|{res}| {e.target.upper()}")
    lines.append("")

    for pid in spofs:    lines.append(f"    class {pid.upper()} spof")
    for pid in compound: lines.append(f"    class {pid.upper()} compound")
    for pid in survivors: lines.append(f"    class {pid.upper()} survivor")
    other = set(cm.pods) - spofs - compound - survivors
    for pid in other: lines.append(f"    class {pid.upper()} pod")
    lines.append("```")
    return "\n".join(lines)


def build_mermaid_cascade_waterfall(cm: ColonyMap) -> str:
    aquifer_chain = next(
        (c for c in cm.metrics.chained_cascades if c.primary_trigger == "aquifer"), None,
    )
    if aquifer_chain is None:
        return "*No chained cascade for Aquifer.*"

    lines: list[str] = []
    lines.append("```mermaid")
    lines.append("graph TD")
    lines.append("    classDef trigger  fill:#ff6b6b,stroke:#c92a2a,color:white,font-weight:bold")
    lines.append("    classDef inferred fill:#ffd43b,stroke:#fab005,color:#333")
    lines.append("    classDef life     fill:#fa5252,stroke:#c92a2a,color:white,font-weight:bold")
    lines.append("    classDef step     fill:#e9ecef,stroke:#868e96,color:#333")
    lines.append("    classDef survivor fill:#51cf66,stroke:#2f9e44,color:white")
    lines.append("")

    helios_offset = aquifer_chain.inference_parameters.get(
        "helios_coolant_degradation_hours", 48.0,
    )

    lines.append(f"    T0[\"T+0<br/>Aquifer fails\"]:::trigger")
    lines.append(f"    T48[\"T+{helios_offset:.0f}h (inferred)<br/>Helios degrades\"]:::inferred")
    lines.append(f"    T0 ==> T48")
    lines.append("")

    timed = sorted(
        [e for e in aquifer_chain.events
         if e.cumulative_hours is not None and e.pod_id != "helios"],
        key=lambda e: e.cumulative_hours,
    )
    for evt in timed:
        node = f"E_{evt.pod_id.upper()}"
        label = f"T+{evt.cumulative_hours:.0f}h<br/>{pod_name(cm, evt.pod_id)}<br/><i>{evt.lost_resource}</i>"
        lines.append(f"    {node}[\"{label}\"]")
        if evt.is_life_critical:
            lines.append(f"    class {node} life")
        else:
            lines.append(f"    class {node} step")
        lines.append(f"    T48 --> {node}")
    lines.append("")

    if aquifer_chain.survivors:
        for sv in aquifer_chain.survivors:
            node = f"S_{sv.pod_id.upper()}"
            lines.append(f"    {node}[\"{pod_name(cm, sv.pod_id)}<br/>survives\"]:::survivor")
    lines.append("```")
    return "\n".join(lines)


def build_mermaid_survivors(cm: ColonyMap) -> str:
    aquifer_chain = next(
        (c for c in cm.metrics.chained_cascades if c.primary_trigger == "aquifer"), None,
    )
    if aquifer_chain is None or not aquifer_chain.survivors:
        return ""

    lines: list[str] = []
    lines.append("```mermaid")
    lines.append("graph LR")
    lines.append("    classDef survivor fill:#51cf66,stroke:#2f9e44,color:white,font-weight:bold")
    lines.append("    classDef resource fill:#e3fafc,stroke:#15aabf,color:#0c8599")
    lines.append("")

    for sv in aquifer_chain.survivors:
        sv_name = pod_name(cm, sv.pod_id)
        sv_node = sv.pod_id.upper()
        lines.append(f"    {sv_node}([\"{sv_name}<br/>{sv.reason}\"]):::survivor")
        for i, ev in enumerate(sv.evidence):
            if ev.startswith("metadata:"):
                ev_text = ev[len("metadata:"):]
            else:
                continue
            res_node = f"{sv_node}_R{i}"
            label = ev_text[:40]
            lines.append(f"    {res_node}[\"{label}\"]:::resource")
            lines.append(f"    {sv_node} --> {res_node}")
    lines.append("```")
    return "\n".join(lines)


# ── Section 9: Methodology appendix ─────────────────────────────────────────

def build_methodology_appendix(cm: ColonyMap, citation_summary: dict, llm_audit: dict) -> str:
    lines = ["## Appendix: Methodology", ""]
    lines.append(
        "This report was produced by an autonomous agent in two phases:"
    )
    lines.append("")
    lines.append("1. **Mapping** (`run_mapping.sh`) — five sequential phases:")
    lines.append("   - Phase 0: BFS discovery of all pods from the gateway")
    lines.append("   - Phase 1: parallel async crawl of 6 endpoints per pod")
    lines.append("   - Phase 2: edge reconciliation (`/dependencies` vs `/supplies`)")
    lines.append("   - Phase 3: unified timeline assembly (logs + comms)")
    lines.append("   - Phase 4: three-layer metrics (structural / operational / LLM)")
    lines.append("     plus chained cascade simulation")
    lines.append("   - Phase 5: assembly into `map.json`")
    lines.append("")
    lines.append("2. **Reporting** (`run_reporting.sh`) — this document. "
                 "Two LLM calls (crisis narrative, recommendations) with "
                 "structured tool-use; everything else is rendered "
                 "deterministically from `map.json`.")
    lines.append("")

    # ── Citation grounding audit ─────────────────────────────────────────
    lines.append("### Validation")
    lines.append("")
    lines.append("**Citation grounding audit** (`report/audit.py`)")
    lines.append("")
    lines.append(f"- Total citations: **{citation_summary['total_citations']}**")
    for kind, n in citation_summary["by_kind"].items():
        avail = citation_summary["available_ids"].get(kind, "?")
        lines.append(f"  - `{kind}`: {n} (available IDs: {avail})")
    c_status = "PASS" if citation_summary["unresolved_count"] == 0 else "FAIL"
    lines.append(f"- Unresolved: **{citation_summary['unresolved_count']}** — `{c_status}`")
    if citation_summary["unresolved"]:
        lines.append("")
        lines.append("  Unresolved citation IDs:")
        for c in citation_summary["unresolved"][:10]:
            lines.append(f"  - `{c}`")
    lines.append("")

    # ── LLM signal audit ─────────────────────────────────────────────────
    lines.append("**LLM enrichment audit** (`report/validation.py`)")
    lines.append("")
    t = llm_audit["tallies"]
    l_status = "PASS" if (t["bad_pod_id"] == 0 and t["bad_timestamp"] == 0) else "FAIL"
    lines.append(f"- Signals evaluated: **{llm_audit['signal_count']}**")
    lines.append(f"- Bad pod IDs: **{t['bad_pod_id']}**")
    lines.append(f"- Bad evidence timestamps: **{t['bad_timestamp']}**")
    lines.append(f"- `is_formally_declared` mismatches (SUPPLY_ONLY edges "
                 f"not counted as operational): **{t['wrong_formally_declared']}**")
    lines.append(f"- Result: `{l_status}`")
    lines.append("")

    # ── Test suite summary ────────────────────────────────────────────────
    lines.append("**Test suite** (`report/validation.py --tests-only`)")
    lines.append("")
    lines.append("Four test classes, run offline against the colony artifacts:")
    lines.append("")
    lines.append("| Class | Cases | Coverage |")
    lines.append("|---|---:|---|")
    lines.append("| `CitationSanitizerTests` | 18 | strip/keep decisions for all 16 unresolved + 2 mixed-text cases |")
    lines.append("| `EvidenceListSanitizerTests` | 3 | evidence list filtering |")
    lines.append("| `CitationIndexTests` | 7 | index building: key presence, directive/comms/edge/log counts |")
    lines.append("| `LLMSignalAuditTests` | 4 | pod-ID validity, timestamp validity, signal presence |")
    lines.append("")

    lines.append("Decision log: `candidate/design_log.md`")
    lines.append("")
    return "\n".join(lines)


# ── Orchestrator ────────────────────────────────────────────────────────────

async def run(
    map_path: Path,
    output_path: Path,
    api_key: str | None,
) -> tuple[ColonyMap, dict]:
    logger.info("═" * 60)
    logger.info("  SELENE REPORTING AGENT")
    logger.info("  Map input:  %s", map_path)
    logger.info("  Output:     %s", output_path)
    logger.info("  LLM key:    %s", "configured" if api_key else "not set — using deterministic fallbacks")
    logger.info("═" * 60)

    if not map_path.exists():
        logger.error("map.json not found at %s — run run_mapping.sh first", map_path)
        sys.exit(1)

    cm = ColonyMap.model_validate_json(map_path.read_text())
    logger.info("Loaded ColonyMap: %d pods, %d edges, %d timeline events",
                cm.pod_count(), len(cm.edges), len(cm.timeline))

    llm = LLMClient(api_key)

    sections: list[str] = []

    logger.info("Section 1: executive summary")
    sections.append(build_executive_summary(cm))

    logger.info("Section 2: crisis narrative (LLM)")
    sections.append(await build_crisis_section(cm, llm))

    logger.info("Mermaid: operational dependency graph")
    sections.append("### Operational Dependency Graph\n\n" + build_mermaid_dependency_graph(cm))

    logger.info("Section 3: cascade path")
    sections.append(build_cascade_path(cm))

    logger.info("Section 4: timeline + cascade waterfall mermaid")
    sections.append(build_timeline(cm))
    sections.append("### Cascade Waterfall\n\n" + build_mermaid_cascade_waterfall(cm))

    logger.info("Section 5: survivors + survivor mermaid")
    sections.append(build_survivors(cm))
    sv_mermaid = build_mermaid_survivors(cm)
    if sv_mermaid:
        sections.append("### Survivor Resilience Map\n\n" + sv_mermaid)

    logger.info("Section 6: six critical signals")
    sections.append(build_signals(cm))

    logger.info("Section 7: reconciliation summary")
    sections.append(build_reconciliation_summary(cm))

    logger.info("Section 8: recommendations (LLM)")
    sections.append(await build_recommendations(cm, llm))

    # Citation audit must happen on the full text BEFORE rendering the appendix
    pre_appendix = "\n\n".join(sections)
    citation_summary = summarise_audit(pre_appendix, cm)
    logger.info(
        "Citation audit: %d total, %d unresolved",
        citation_summary["total_citations"],
        citation_summary["unresolved_count"],
    )
    for c in citation_summary["unresolved"][:5]:
        logger.warning("  unresolved: %s", c)

    # LLM enrichment signal audit
    import json as _json
    raw_data = _json.loads(map_path.read_text())
    llm_audit = _audit_llm_signals(raw_data)
    logger.info(
        "LLM signal audit: %d signals, %d issues (pod=%d ts=%d declared=%d)",
        llm_audit["signal_count"],
        llm_audit["issue_count"],
        llm_audit["tallies"]["bad_pod_id"],
        llm_audit["tallies"]["bad_timestamp"],
        llm_audit["tallies"]["wrong_formally_declared"],
    )

    sections.append(build_methodology_appendix(cm, citation_summary, llm_audit))

    report_text = "\n\n".join(sections) + "\n"
    output_path.write_text(report_text)
    size_kb = output_path.stat().st_size / 1024
    logger.info("report.md written — %.1f KB", size_kb)

    if DEFAULT_DELIVERABLE_DIR and DEFAULT_DELIVERABLE_DIR.is_dir():
        import shutil
        shutil.copy2(output_path, DEFAULT_DELIVERABLE_DIR / "report.md")
        logger.info("report.md duplicated → %s/report.md", DEFAULT_DELIVERABLE_DIR)

    return cm, citation_summary


if __name__ == "__main__":
    out_dir = DEFAULT_OUTPUT_DIR
    out_dir.mkdir(parents=True, exist_ok=True)
    asyncio.run(run(
        map_path=out_dir / "map.json",
        output_path=out_dir / "report.md",
        api_key=DEFAULT_LLM_API_KEY,
    ))
